378 1 day jwt long shelf life
DFE-Digital/publish-teacher-training pull request #1429
Opened 2020-11-11 17:01 UTC by defong

### Context

### Changes proposed in this pull request

### Guidance to review

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [ ] Product Review

2020-11-12 15:20 UTC, defong commented
![](https://github.trello.services/images/mini-trello-icon.png) [[1 day] JWT long shelf life](https://trello.com/c/N0SzJtAH/378-1-day-jwt-long-shelf-life)

2020-11-13 10:12 UTC, darokel approved these changes

2020-11-13 22:28 UTC, dankmitchell approved these changes

2020-11-16 09:47 UTC, gpeng requested changes

2020-11-16 09:47 UTC, gpeng commented on app/services/jwt/encode_service.rb
> +    class << self
We can `include ServicePattern` to get this bit.

2020-11-17 08:06 UTC, gpeng approved these changes

2020-11-17 08:22 UTC, merged