601 signin page for publish
DFE-Digital/publish-teacher-training pull request #1477
Opened 2020-12-18 20:16 UTC by defong

### Context

signin page for publish

### Changes proposed in this pull request
Removed the basket ball team of booleans.
Added an `intermittent signin page` for publish
Fixed 400+ broken tests * 2 times
Amended azure related settings
Amended readme to reflect this change

### Guidance to review
Pull down the code and go though the 
- 3 mutually exclusive ways to login, 

As well as per the related environment yml vs actual environment expectations:
- defaulted production, 
- defaulted qa,
- defaulted staging,
- defaulted localhost .

The whole user journey has changed.

Originally when navigating to any authenticated paths, inclusive of the root path, the user will be redirected to
- `/signin` 

Then they will be further redirected to one of the following:
- `DfE Sign In`
- `Persona`
Or 
- the `Magic` page is shown.

Now the user is redirected to `/sign-in` of which the `intermittent Sign In page` will be shown or the `Magic` page is shown.

The `mutually exclusive` applies from route/endpoint down.

- Non-Production environments
  - `persona`

- Production environments
  - `dfe_signin`
  - `magic`

> We managed to introduced 6 various booleans over extended period of time that controls this in very fine grain manner with various implied implicit or explicit expectation. ie you configure those 6 boolean to allow you to log in proper but the same settings fails to log you out, or the settings for productions settings can be easy mistaken intertwined non-productions settings .

Builds on top of https://github.com/DFE-Digital/publish-teacher-training/pull/1467 whereby @gpeng was the confused survivor of  

> The greater the drift from localhost to mimic a production like settings causes caveats and subtleties and conflicts with the subliming of easy of development, as well as resurrecting the `It works on my machine` heresy.

The PR started as `add gem` then `add sign in page` then :exploding_head: 

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [ ] Product Review

2020-12-18 20:18 UTC, defong commented
![](https://github.trello.services/images/mini-trello-icon.png) [Signin page for publish](https://trello.com/c/xyqQKa2L/601-signin-page-for-publish)

2020-12-18 20:19 UTC, defong commented
![](https://github.trello.services/images/mini-trello-icon.png) [Signin page for publish](https://trello.com/c/xyqQKa2L/601-signin-page-for-publish)

2021-01-06 09:25 UTC, gpeng requested changes
Just a couple of little comments but this looks awesome. What a headache. We'll need to give this a good run out on QA and try setting the mode from the env. It would be good to have the env variables set up, even though the config is in here. We'll also need to add some documentation for switching mode.

2021-01-11 11:48 UTC, defong commented on config/settings/production.yml
> +# # Wield magic
It's __explicit__ by `default` in the same veins as __secure__ by `default`

Changing the `mode` is an operation concerns, this only serves as a comment and last resort.

2021-01-12 09:55 UTC, gpeng requested changes
Can we change the references to `magic` and `magic?` to `magic_link`. Or maybe `email_link?`. Logging in by `magic` doesn't seem very helpful 😆 I think this is looking good now though. I still feel we should be explicit in each environment so as it's clear what the default is. It's an important feature.

2021-01-12 21:26 UTC, defong commented on config/settings/production.yml
> +# # Wield magic
Also added to file now

2021-01-12 21:29 UTC, defong commented
> Can we change the references to `magic` and `magic?` to `magic_link`. Or maybe `email_link?`. Logging in by `magic` doesn't seem very helpful laughing I think this is looking good now though. I still feel we should be explicit in each environment so as it's clear what the default is. It's an important feature.

Fair enough, but we are so so so keeping this method

https://github.com/DFE-Digital/publish-teacher-training/blob/7b856accff17a22ca372a52209d73a21aef77a1f/app/controllers/sessions_controller.rb#L31

2021-01-15 12:21 UTC, merged