[1493] Add UKPRN text field to the contact details section
DFE-Digital/publish-teacher-training pull request #1609
Opened 2021-04-20 12:33 UTC by avinhurry

### Context

We are starting to collect UKPRN numbers from all providers. This PR surfaces the field on the contact details page. 

The provider table already has a UKPRN column.

### Changes proposed in this pull request

Add UKPRN text field to the contact details section

### Guidance to review

- Pull down the code and boot up the server
- Navigate to `organisations/provider_code/2021/contact`
- Enter a number in the UKPRN box and save the changes
- Boot up the rails console and check that the change has been saved

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [ ] Product Review

2021-04-20 12:34 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Add the UI in the contact details section to capture UKPRN](https://trello.com/c/FmBnQWnA/1493-s-add-the-ui-in-the-contact-details-section-to-capture-ukprn)

2021-04-20 12:52 UTC, defong requested changes
can you add the tests please

https://github.com/DFE-Digital/publish-teacher-training/blob/f23ecd81fe2a769b239359fe35719a529871578e/spec/features/providers/contact_spec.rb

2021-04-20 15:57 UTC, defong approved these changes

2021-04-20 15:57 UTC, defong commented on spec/features/providers/contact_spec.rb
> +          ukprn: "12345678"
i don't think you need this as its in the factory

2021-04-21 10:30 UTC, jesseyuen approved these changes

2021-04-21 10:33 UTC, merged