Visa sponsorship course preview
DFE-Digital/publish-teacher-training pull request #1736
Opened 2021-06-21 08:48 UTC by stevehook

### Context

This PR is a follow up to https://github.com/DFE-Digital/publish-teacher-training/pull/1725

It adds an _International students_ section to the course preview page.

See https://trello.com/c/I2K4fchq/3441-add-visa-flow-to-publish

### Changes proposed in this pull request

- [x] Add section to the course preview page that is only rendered when the `rollover.prepare_for_next_cycle` feature flag is switched on. Render one of these two variations depending on whether the provider has answer the visa sponsorship questions or not.
<img width="774" alt="image" src="https://user-images.githubusercontent.com/450843/122731600-5f7c8480-d273-11eb-8ade-bf898b6d0d25.png">

<img width="774" alt="image" src="https://user-images.githubusercontent.com/450843/122731693-74591800-d273-11eb-8d39-6d41d0600802.png">

- [ ] Rebase onto `master`

### Guidance to review

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [ ] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally
- [ ] Product Review

2021-06-21 12:39 UTC, paulrobertlloyd requested changes

2021-06-21 12:39 UTC, paulrobertlloyd commented on app/views/courses/preview/_international_students.html.erb
> +  <p></p>
```suggestion
  <% if @provider.declared_visa_sponsorship? %>
    <p class="govuk-body">
      We 
      <%= @provider.cannot_sponsor_visas? ? "cannot" : "can" %>
      <%= govuk_link_to(
        visa_sponsorship_short_status(@provider),
        "https://www.gov.uk/government/publications/train-to-teach-in-england-non-uk-applicants/train-to-teach-in-england-non-uk-applicants#visas-and-immigration",
      ) %><%= @provider.cannot_sponsor_visas? ? "." : ", but this is not guaranteed." %>
    </p>
  <% else %>
    <div class="govuk-inset-text app-inset-text app-inset-text--important">
      <p class="govuk-heading-s">
        Please add details
        <%= govuk_link_to(
          "about visa sponsorship",
          provider_recruitment_cycle_visas_path(@provider.provider_code, @provider.recruitment_cycle_year),
        ) %>
      </p>
    </div>
  <% end %>
```

2021-06-25 12:38 UTC, paulrobertlloyd approved these changes

2021-06-28 11:23 UTC, defong approved these changes
LGTM

2021-06-28 11:35 UTC, merged