[233] Surface financial incentives on course page
DFE-Digital/publish-teacher-training pull request #2828
Opened 2022-07-11 12:58 UTC by darokel

### Context

https://trello.com/c/hiRC3Z1m/233-surface-financial-incentives-on-course-page

### Changes proposed in this pull request

- Surfaces financial incentive detail for courses on the course show page
- Shows relevant details for the following scenarios:
- - Financial incentive is not available for the course
- - Financial incentive is available (scholarship and bursary, as well as just bursary option)
- - Financial incentive isn't available yet (during rollover/transition into next cycle)

### Guidance to review

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased main
- [x] Cleaned commit history
- [x] Tested by running locally

2022-07-12 14:47 UTC, defong requested changes
![image](https://user-images.githubusercontent.com/470137/178518499-582fadef-6ca1-4fa6-a2f4-3cbfde7d3bf2.png)

2022-07-13 09:19 UTC, simonwhatley commented
@darokel Financial support is split into two:
- "Financial support you offer" - this has a change link
- "Financial support from the government" - this doesn't have a change link as it is derived from policy

Remove the full stop from the end of "Information not yet available"

2022-07-13 12:34 UTC, defong approved these changes

2022-07-13 12:41 UTC, simonwhatley approved these changes

2022-07-13 13:31 UTC, merged