922 migrate find cycles feature part 2
DFE-Digital/publish-teacher-training pull request #3224
Opened 2023-01-04 13:04 UTC by avinhurry

### Context

This is the sequel to #3205. 

### Changes proposed in this pull request

- Port over `find_has_closed` functionality for the cycle switcher.
- Add routes and view
- Add a redirect to the new view from the start page if "find has closed" is chosen on the cycle switcher.

- Port over find_has_reopened
- Add dynamic years 

### Guidance to review

Do the last two options on the cycle switcher work as we expect? Have I missed anything?

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased main
- [ ] Cleaned commit history
- [ ] Tested by running locally

2023-01-04 13:04 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate Find `/cycles` feature part 2](https://trello.com/c/iNM5JJcy/922-migrate-find-cycles-feature-part-2)

2023-01-09 09:29 UTC, defong requested changes

2023-01-09 09:29 UTC, defong commented on app/controllers/find/search/locations_controller.rb
> +      end
It should be more of 

https://github.com/DFE-Digital/find-teacher-training/blob/e08f05ec6d092abf98e600cc41296c9831d70d6b/app/controllers/application_controller.rb#L9


Keep it down!

2023-01-09 17:24 UTC, defong approved these changes

2023-01-10 10:21 UTC, merged