[1361] Update dates in line with Apply timetable
DFE-Digital/publish-teacher-training pull request #3621
Opened 2023-06-07 15:56 UTC by avinhurry

### Context

Updating our dates for the current and next cycle in line with Apply: 

### Guidance to review

Compare the dates in this PR with the dates in the links below and ensure they match up.

- https://github.com/DFE-Digital/apply-for-teacher-training/blob/fd4bffb0489c5281a0095086a5f6092bf90f0e74/app/services/cycle_timetable.rb#LL67C8-L67C8

- https://www.apply-for-teacher-training.service.gov.uk/provider/service-guidance/dates-and-deadlines

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased main
- [x] Cleaned commit history
- [x] Tested by running locally
- [ ] Inform data insights team due to database changes

2023-06-07 15:58 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update dates for rollover](https://trello.com/c/xKllRlMm/1361-update-dates-for-rollover)

2023-06-08 07:18 UTC, goodviber approved these changes
lgtm

2023-06-08 08:24 UTC, defong requested changes
Looks wrong?

![image](https://github.com/DFE-Digital/publish-teacher-training/assets/470137/09b56f09-08ec-4a15-9d1e-5319326ac88c)

2023-06-08 13:29 UTC, defong approved these changes

2023-06-08 14:11 UTC, merged