wip
DFE-Digital/publish-teacher-training pull request #4243
Opened 2024-05-31 13:49 UTC by elceebee

### Context

### Changes proposed in this pull request

### Guidance to review

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased main
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [ ] Inform data insights team due to database changes

2024-05-31 15:37 UTC, elceebee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Publish: Cut down Course Length & Fees page - Remove financial_support](https://trello.com/c/7lb2uHHF/1577-publish-cut-down-course-length-fees-page-remove-financialsupport)

2024-05-31 15:37 UTC, elceebee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Publish: Cut down Course Length & Fees page - move Fees to its own page](https://trello.com/c/BgWXv7hr/1575-publish-cut-down-course-length-fees-page-move-fees-to-its-own-page)

2024-06-03 09:07 UTC, tomas-stefano approved these changes

2024-06-03 11:27 UTC, inulty-dfe requested changes
Nice work, very clean :100: 

Only real concern is mixing up of namespaces

2024-06-03 11:27 UTC, inulty-dfe commented on app/forms/publish/course_fees_and_financial_support_form.rb
> +    include FundingTypeFormMethods
Let's put the includes together

2024-06-03 11:27 UTC, inulty-dfe commented on app/views/publish/courses/fees_and_financial_support/_guidance.html.erb
> +  <%= render Find::Utility::AdviceComponent::View.new(title: "Financial support from the government") do %>
This has the namespace `Find` but we're using it in Publish views. Can we find a way to make this work?

Maybe remove it from the Find namespace into a shared one or something?

2024-06-03 11:27 UTC, inulty-dfe commented on app/views/publish/courses/fees_and_financial_support/_guidance.html.erb
> +  <%= render Find::Utility::AdviceComponent::View.new(title: "Financial support from the government") do %>
Same for all the components and views below

2024-06-03 11:27 UTC, inulty-dfe commented on spec/features/publish/editing_fees_and_financial_support_spec.rb
> +    and_i_enter_invalid_data
```suggestion
    and_i_enter_too_many_words
```

2024-06-06 11:49 UTC, dcyoung-dev approved these changes

2024-06-06 12:41 UTC, merged