1734 bug copy content drop down disappears after validation
DFE-Digital/publish-teacher-training pull request #4275
Opened 2024-06-13 13:03 UTC by elceebee

### Context
A bug exists such that the course to copy from list does not render after validation on screens where the option exists.

[Trello card](https://trello.com/c/B6ZkPD7b)

### Changes proposed in this pull request
This PR fetches this list of courses for rendering after validation and adds relevant specs

### Guidance to review

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased main
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [ ] Inform data insights team due to database changes

2024-06-13 15:48 UTC, elceebee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: "Copy content" drop down disappears after validation](https://trello.com/c/B6ZkPD7b/1734-bug-copy-content-drop-down-disappears-after-validation)

2024-06-14 11:35 UTC, inulty-dfe requested changes
Looks pretty good to me!

Couple of small change requests

2024-06-14 11:35 UTC, inulty-dfe commented on app/components/providers/copy_course_content_warning_component.rb
> +    include I18n
Better to just call `I18n.t` instead of including all instance methods to this scope

2024-06-14 11:35 UTC, inulty-dfe commented on spec/features/publish/courses/editing_course_gcse_requirements_copy_content_spec.rb
> +      (find_link 'Accept pending GCSE')[:href].remove('#')
```suggestion
      find_link('Accept pending GCSE')[:href].remove('#')
```

I immediately get distracted if the opening parenthesis is there, can we make it conventional please?
And for all the others

2024-06-14 12:37 UTC, tomas-stefano approved these changes

2024-06-14 13:54 UTC, inulty-dfe approved these changes
Missed a couple :eyes:

2024-06-14 13:54 UTC, inulty-dfe commented on spec/features/publish/courses/editing_course_gcse_requirements_copy_content_spec.rb
> +    expect((find_link 'Additional GCSE equivalencies')[:href].remove('#')).to eq(find_field('Details about equivalency tests you offer or accept')[:id])
Missed these two :eyes:

2024-06-14 13:54 UTC, inulty-dfe commented on spec/features/publish/courses/editing_course_subject_requirements_copy_content_spec.rb
> +    expect((find_link 'Degree subject requirements')[:href].remove('#')).to eq(find_field('Degree subject requirements')[:id])
Missed these two :eyes:

2024-06-14 14:58 UTC, merged